#heading(level: 1, numbering: none)[Streszczenie] <streszczenie>

Przedmiotem pracy dyplomowej jest projekt oraz implementacja serwerowego systemu automatyki domowej zbudowanego w oparciu o mikrokontrolery z rodziny ESP oraz protokół komunikacyjny MQTT. Głównym celem projektu było opracowanie skalowalnej oraz działającej lokalnie architektury inteligentnego domu, a następnie poddanie jej badaniom pod kątem bezpieczeństwa w sieci.

W części teoretycznej zostaje opisana platforma Home Assistant, która jest centralnym środowiskiem zarządzania automatyką domową. Następnie scharakteryzowany zostaje protokół MQTT, czyli sposób na wymianę danych między urządzeniami Internetu Rzeczy. Omówiona zostaje również platforma Docker, która jest narzędziem konteneryzacji usług serwerowych. Uzupełnieniem tego przeglądu jest zestawienie dostępnych rozwiązań sprzętowych dla systemów tego typu.

W części praktycznej zaprojektowano i uruchomiono trójwarstwowy system automatyki domowej. Warstwę fizyczną tworzą mikrokontrolery ESP32, które podzielono ze względu na zastosowanie. Pierwszy z nich to czujnik publikujący dane telemetryczne, a drugi to element wykonawczy. Rolę warstwy sieciowej pełni broker MQTT Mosquitto, a warstwę aplikacyjną stanowi platforma Home Assistant uruchomiona w kontenerze Docker na serwerze z systemem Debian.

Kluczowym elementem pracy są badania bezpieczeństwa wdrożonego systemu. Badania te przeprowadzono na przygotowanym stanowisku badawczym, na którym sieć IoT była fizycznie i logicznie odizolowana od sieci domowej przy użyciu routera TP-Link. Testy w warstwie sieciowej pozwoliły zweryfikować skuteczność izolacji ruchu ICMP w trzech różnych scenariuszach konfiguracyjnych. Z kolei testy warstwy aplikacji potwierdziły, że wymóg uwierzytelniania MQTT hasłem skutecznie blokuje nieautoryzowany dostęp do komunikacji z brokerem. Zbadano również bezpieczny zdalny dostęp do interfejsu Home Assistant za pomocą sieci VPN Tailscale, która działa na protokole WireGuard.

Uzyskane wyniki prowadzą do wniosku, że architektura łącząca separację sieci, uwierzytelnianie komunikacji z brokerem oraz tunelowanie VPN tworzy solidny i niezawodny fundament bezpiecznego systemu automatyki domowej.

#heading(level: 1, numbering: none)[Abstract] <abstract>

This master's thesis presents the design and implementation of a server-based home automation system built upon ESP microcontrollers and the MQTT communication protocol. The primary objective was to develop a scalable, locally operating smart home architecture and to subsequently carry out a thorough security assessment of the resulting system.

The theoretical section introduces the Home Assistant platform as a central home automation management environment, describes the MQTT protocol as a lightweight data exchange bus for Internet of Things (IoT) devices, and presents the Docker platform as a containerization tool for server-side services. A survey of hardware solutions compatible with the Home Assistant ecosystem is also included.

In the practical part, a three-layer home automation system was designed and deployed. The physical layer is built around ESP32 microcontrollers, for which two distinct types of node firmware were developed: a sensor node (Node-1) that publishes telemetry data — temperature, humidity, and atmospheric pressure — and an actuator node (Node-2) that maintains bidirectional communication using an MQTT Self-Discovery mechanism, allowing the device to register itself automatically in the management system without any manual modification of configuration files. The network layer is handled by the Mosquitto MQTT broker, while the application layer consists of the Home Assistant platform running inside a Docker environment on a Debian-based server.

A particularly significant component of the thesis is the security research conducted on the deployed system. Experiments were carried out on a dedicated test bench in which the IoT network was physically and logically separated from the home network by means of a TP-Link router. Layer 3 network tests examined the effectiveness of ICMP traffic isolation across three distinct configuration scenarios. Application-layer tests (Layer 4+) confirmed that enforcing password-based authentication on the MQTT broker effectively prevents unauthorized access to the communication bus. In parallel, secure remote access to the Home Assistant interface was verified through the Tailscale VPN network, which is based on the WireGuard protocol and entirely removes the need to expose any services on the public Internet.

The research outcomes indicate that an architecture combining IoT network segmentation, broker-level authentication, and VPN tunneling establishes a robust and dependable foundation for a secure home automation system that is resilient to common unauthorized-access attack vectors.
