#heading(level: 1, numbering: none)[Wykaz ważniejszych oznaczeń i skrótów] <oznaczenia>

#set terms(separator: [ -- ], hanging-indent: 1.5em)

/ API: *Application Programming Interface* (interfejs programowania aplikacji)
/ CLI: *Command Line Interface* (interfejs wiersza poleceń)
/ ESP: *Espressif Systems* (producent mikrokontrolerów z rodziny ESP32)
/ GPIO: *General-Purpose Input/Output* (port wejścia/wyjścia ogólnego przeznaczenia)
/ HA: *Home Assistant* (otwarty system automatyki domowej)
/ HTTP: *Hypertext Transfer Protocol* (protokół przesyłania dokumentów hipertekstowych)
/ HTTPS: *Hypertext Transfer Protocol Secure* (szyfrowana wersja protokołu HTTP)
/ ICMP: *Internet Control Message Protocol* (protokół komunikatów kontrolnych sieci Internet)
/ IDE: *Integrated Development Environment* (zintegrowane środowisko programistyczne)
/ IDS: *Intrusion Detection System* (system wykrywania intruzów)
/ IoT: *Internet of Things* (Internet Rzeczy)
/ IP: *Internet Protocol* (protokół internetowy)
/ JSON: *JavaScript Object Notation* (format zapisu danych strukturyzowanych)
/ LAN: *Local Area Network* (lokalna sieć komputerowa)
/ LWT: *Last Will and Testament* (mechanizm „ostatniej woli” w protokole MQTT)
/ MQTT: *Message Queuing Telemetry Transport* (lekki protokół komunikacyjny publish-subscribe)
/ NTP: *Network Time Protocol* (protokół synchronizacji czasu w sieci)
/ OSI: *Open Systems Interconnection* (model odniesienia komunikacji w sieciach komputerowych)
/ OTA: *Over-the-Air* (bezprzewodowa aktualizacja oprogramowania)
/ QoS: *Quality of Service* (jakość usług w protokole MQTT)
/ RISC-V: *Reduced Instruction Set Computer - V* (otwarta architektura procesora o zredukowanym zestawie instrukcji)
/ SSL: *Secure Sockets Layer* (protokół bezpiecznej transmisji danych)
/ TCP: *Transmission Control Protocol* (protokół sterowania transmisją)
/ TLS: *Transport Layer Security* (rozwinięcie protokołu SSL zapewniające bezpieczną transmisję danych)
/ VPN: *Virtual Private Network* (wirtualna sieć prywatna)
/ WAN: *Wide Area Network* (rozległa sieć komputerowa)
/ WLAN: *Wireless Local Area Network* (bezprzewodowa sieć lokalna)
/ YAML: *YAML Ain't Markup Language* (format serializacji danych o strukturze hierarchicznej)
