Home Assistant - to darmowe i otwarte oprogramowanie, które umożliwia scentralizowaną automatyzację domu. Jest to kontroler inteligentnego domu, który pełni zarówno funkcję centrali inteligentnego domu (czasami nazywanej „inteligentną bramką”), jak i platformy integracyjnej zaprojektowanej z myślą o interoperacyjności, umożliwiając użytkownikom sterowanie z jednego punktu i automatyzację różnych inteligentnych urządzeń domowych z centralnej lokalizacji, niezależnie od producenta czy marki.  

Projekt został rozpoczęty jako aplikacja w Pythonie przez Paulusa Schoutsena we wrześniu 2013 r. i po raz pierwszy opublikowany publicznie w serwisie GitHub w listopadzie 2013 r. 

Integracje: Integracje to elementy oprogramowania, które umożliwiają Home Assistant łączenie się z innymi programami i platformami. Na przykład produkt firmy Philips o nazwie Hue korzystałby z integracji Philips Hue i umożliwiałby Home Assistant komunikację ze sprzętowym kontrolerem Hue Bridge. Wszystkie urządzenia kompatybilne z Home Assistant podłączone do Hue Bridge byłyby widoczne w Home Assistant jako urządzenia. 

Urządzenia: Urządzenia to logiczna grupa obejmująca jeden lub więcej obiektów. Urządzenie może reprezentować urządzenie fizyczne, które może mieć jeden lub więcej czujników. Czujniki pojawiają się jako obiekty powiązane z urządzeniem. Na przykład czujnik ruchu jest reprezentowany jako urządzenie. Może on zapewniać wykrywanie ruchu, temperaturę i poziom oświetlenia jako obiekty. Obiekty mają stany takie jak „wykryto” w przypadku wykrycia ruchu i „wyczyść”, gdy nie ma ruchu. 

Encje: Encje to podstawowe elementy składowe do przechowywania danych w Home Assistant. Encja reprezentuje czujnik, aktora lub funkcję w Home Assistant. Encje służą do monitorowania właściwości fizycznych lub sterowania innymi encjami. Encja jest zazwyczaj częścią urządzenia lub usługi. Encje mają stany. 

Obszary: Obszar w Home Assistant to logiczna grupa urządzeń i obiektów, które mają odpowiadać obszarom (lub pomieszczeniom) w świecie fizycznym: w Twoim domu. Na przykład obszar salonu grupuje urządzenia i obiekty w Twoim salonie. Obszary pozwalają na kierowanie zgłoszeń serwisowych do całej grupy urządzeń, na przykład poprzez wyłączenie wszystkich świateł w salonie. Są to lokalizacje w Twoim domu, takie jak salon lub parkiet taneczny. Obszary można przypisać do pięter. 

Automatyzacje: Zestaw powtarzalnych działań, które można skonfigurować tak, aby uruchamiały się automatycznie. Automatyzacje składają się z trzech kluczowych komponentów: Zdarzenia wyzwalające, które uruchamiają automatyzację. Na przykład, gdy zachodzi słońce lub czujnik ruchu jest aktywowany. Warunki – opcjonalne testy, które muszą zostać spełnione przed uruchomieniem działania. Na przykład, gdy ktoś jest w domu. Działania współdziałają z urządzeniami, takimi jak włączenie światła. 

Skrypty: Podobnie jak automatyzacje, skrypty to powtarzalne działania, które można uruchomić. Różnica między skryptami a automatyzacjami polega na tym, że skrypty nie posiadają wyzwalaczy. Oznacza to, że skrypty nie mogą zostać uruchomione automatycznie, chyba że zostaną użyte w automatyzacjach. Skrypty są szczególnie przydatne, jeśli wykonujesz te same działania w różnych automatyzacjach lub wyzwalasz je z poziomu pulpitu nawigacyjnego. 

Sceny: Sceny umożliwiają tworzenie predefiniowanych ustawień dla urządzeń. Podobnie jak tryb jazdy w telefonach czy profile kierowców w samochodach, mogą one dostosować otoczenie do Twoich potrzeb. Na przykład, scena podczas oglądania filmu może przyciemnić oświetlenie, włączyć telewizor i zwiększyć głośność. Można ją zapisać jako scenę i używać bez konieczności każdorazowego konfigurowania poszczególnych urządzeń. 

Aplikacje: Aplikacje to aplikacje firm trzecich, które zapewniają dodatkową funkcjonalność w Home Assistant. Aplikacje działają bezpośrednio z Home Assistant, natomiast integracje łączą Home Assistant z innymi aplikacjami. Aplikacje są obsługiwane tylko w systemie operacyjnym Home Assistant. 

 dashboard: Panele to sposób, w jaki widzisz i kontrolujesz swój inteligentny dom w Home Assistant. Składają się z kart i widoków, a można je wizualnie budować metodą „przeciągnij i upuść”, więc nie wymagają kodowania.
